baseURL = 'https://blog.emkaix.at'
languageCode = 'en-us'
title = 'mkx Blog'
theme = 'terminal'
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "mkx"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "show more"
    readMore = "read more"
    readOtherPosts = "read other posts"

    [languages.en.params.logo]
      logoText = "mkx"
      logoHomeLink = "/"

    [languages.en.menu]
    #   [[languages.en.menu.main]]
    #     identifier = "home"
    #     name = "Home"
    #     url = "/"
    #     weight = 1
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
        weight = 2
    #   [[languages.en.menu.main]]
    #     identifier = "showcase"
    #     name = "Showcase"
    #     url = "/showcase"
    #     weight = 3