baseURL = 'https://blog.emkaix.at'
languageCode = 'en-us'
title = 'mkx Blog'
theme = 'terminal'

[pagination]
  pagerSize = 5

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  showMenuItems = 3
  themeColor = "orange"
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    languageName = "English"
    title = "mkx | InfoSec blog"

  [languages.en.params]
    subtitle = "Hello. This is my reverse engineering & hacking blog, with variety development stuff in-between. Explore in-depth reverse engineering tutorials using Ghidra, IDA Pro, and other tools. Learn malware analysis, binary exploitation, and more."
    keywords = "reverse engineering, malware analysis, IDA Pro, Ghidra, binary exploitation, disassembly, static analysis, dynamic analysis, CTF, cybersecurity"
    copyright = "Klaus Hahnenkamp"
    owner = "Klaus Hahnenkamp"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "mkx"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "projects"
        url = "/projects"